name: flutter_net_inspector
description: >
  Flipper/Stetho-like network inspector for Flutter. Dio interceptor
  with real-time mocking, breakpoints, and a VSCode extension dashboard.
version: 0.1.2
homepage: https://github.com/herisulistiyanto/flutter_net_inspector
repository: https://github.com/herisulistiyanto/flutter_net_inspector
issue_tracker: https://github.com/herisulistiyanto/flutter_net_inspector/issues

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  dio: ^5.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
